juntagrico/templates/subscription.html
Disable add member link for non primary users
=> Disable add member link fixes #32

juntagrico/templates/participation.html
Adjusted mismatched div elements and column positioning for "other areas" section  ("weitere Bereiche").
=> Layout fix in participation template

juntagrico/templates/signup.html
=> Fixed typo

juntagrico/templates/newpassword.html
=> Fix new password layout

juntagrico/templates/add_member.html
=> fix cancel link when adding cosubscriber

juntagrico/static/css/juntagrico.css, juntagrico/templates/areas.html, juntagrico/templates/jobs.html, juntagrico/templates/memberjobs.html, juntagrico/templates/menu/user_menu.html, juntagrico/urls.py, juntagrico/views.py, test/test_jobs.py
=> #88 menu rewrite

juntagrico/templates/base.html, juntagrico/templates/cookie.html, juntagrico/templates/createsubscription/add_member_cs.html, juntagrico/templates/createsubscription/select_depot.html, juntagrico/templates/createsubscription/select_shares.html, juntagrico/templates/createsubscription/select_start_date.html, juntagrico/templates/createsubscription/select_subscription.html, juntagrico/templates/createsubscription/summary.html, juntagrico/templates/newpassword.html, juntagrico/templates/no_menu_base.html, juntagrico/templates/registration/login.html, juntagrico/templates/signup.html, juntagrico/templates/welcome.html, juntagrico/views.py
=> no menu where no menu is required

juntagrico/config.py, juntagrico/entity/__init__.py, juntagrico/entity/member.py, juntagrico/entity/share.py, juntagrico/entity/subs.py, juntagrico/mailer.py, juntagrico/management/commands/mailtexts.py, juntagrico/templates/mails/admin/share_created.txt, juntagrico/util/management.py
ich hab mal einen decorator gebastelt sieht meiner meinung nach schöner aus
vorallem weil man dann auch den verbose name reinnehmen kann
und wenn wir wiedermal in einem anderen kontext so permission reinhauen wollen können wir einfach einen neuen decorator schreiben
sonst müssten wir das verschachtelt machen
permissions = perm1(... perm2(...,(('bla','blub'),)))
=> decorator for christmas

juntagrico/admins/forms/subscription_admin_form.py, juntagrico/lifecycle/sub.py
Otherwise subscriptions can not be created through admin page due to consistency check
=> bugfix: set primary member after saving recipients

juntagrico/templates/snippets/snippet_subscription_change_depot.html, juntagrico/templates/snippets/snippet_subscription_change_extra_sub.html, juntagrico/templates/snippets/snippet_subscription_change_main_member.html, juntagrico/templates/snippets/snippet_subscription_change_size.html, juntagrico/templates/subscription_change.html
=> Pack subscription change rows into snippets

juntagrico/admins/forms/job_copy_form.py
=> Convert aware datetime to local time as initial value

juntagrico/templates/job.html
=> Fix Google Maps link

juntagrico/templates/job.html, juntagrico/views.py
=> #180: Remove job participant link

juntagrico/templates/depot_change.html
=> Fix link depot list change confirmation page

juntagrico/views_subscription.py
=> Fix extra subscription cancel

juntagrico/entity/extrasubs.py
=> Extra subscription cancelable by default

docs/settings.rst, juntagrico/config.py, juntagrico/templates/exports/snippets/snippet_depotlist_header.html
=> Add package to vocabulary for customization

juntagrico/admins/subscription_admin.py, juntagrico/entity/subs.py, juntagrico/forms.py, juntagrico/templates/change_nickname.html, juntagrico/templates/exports/depotlist.html, juntagrico/templates/snippets/snippet_subscription_change_nickname.html, juntagrico/templates/subscription.html, juntagrico/templates/subscription_change.html, juntagrico/urls.py, juntagrico/views_subscription.py, test/test_subs.py
=> Implement optional subscription nickname for depot list

juntagrico/dao/subscriptionproductdao.py, juntagrico/management/commands/generate_depot_list.py
Show products on depot list only if at least one size is depot list visible
=> Show products on depot list only if at least one size is visible

juntagrico/dao/subscriptionproductdao.py, juntagrico/forms.py
=> Show products on create subscription view only if visible childs

juntagrico/templates/subscription.html
=> Fix share count in subscription overview

juntagrico/templates/extra_change.html, juntagrico/templates/size_change.html, juntagrico/templates/subscription.html, juntagrico/views_subscription.py
=> #302 Prevent new extras and parts for canceled subscriptions

juntagrico/templatetags/depot_extras.py
=> #322 Fix depot list extras sums for future deactivation_date

juntagrico/dao/subscriptiondao.py
=> #333 Fix depot admin list remove inactive subscriptions

juntagrico/templates/members.html
=> #341 Fix subscription reference for members list

README.rst
fix #380 by documenting the username and password of the demo deployment
=> fix #380 by documenting the username and password of the demo deployment

docs/1_3_release_notes.rst, juntagrico/admins/forms/job_copy_form.py
=> Include multiplier in job copy form

docs/1_4_release_notes.rst, juntagrico/static/css/juntagrico.css, juntagrico/templates/widgets/assignements.html, juntagrico/templatetags/widgets.py
If a member has to make 3 normal assignments + 2 core assignments and makes 5 normal assignments, the widget showed 0 remaining assignments.
This should fix it.
=> Fix remaining assignments

docs/1_4_release_notes.rst, juntagrico/admins/admin_decorators.py, juntagrico/admins/delivery_admin.py, juntagrico/admins/inlines/subscription_membership_inlines.py, juntagrico/admins/job_admin.py, juntagrico/admins/job_type_admin.py, juntagrico/admins/member_admin.py, juntagrico/admins/one_time_job_admin.py, juntagrico/admins/share_admin.py, juntagrico/admins/subscription_admin.py, juntagrico/entity/jobs.py, juntagrico/entity/subs.py, juntagrico/management/commands/generate_testdata_advanced.py
Decorators: https://docs.djangoproject.com/en/3.2/releases/3.2/#new-decorators-for-the-admin-site
Related fields links: https://docs.djangoproject.com/en/3.2/releases/3.2/#django-contrib-admin
=> use django 3.2 decorators and automatic related object link

docs/1_4_release_notes.rst, juntagrico/static/juntagrico/js/initJobs.js, juntagrico/templates/jobs.html, juntagrico/templates/snippets/snippet_jobs.html
Suggestion for #257 with option to filter for minimum number of free slots. Helpful for groups of people trying to find a job.
=> #257 filter free slots on jobs table

juntagrico/templates/management_lists/assignments.html
One way to fix #439
It seems that datatables does not recognize this localized comma as a floating point.
I went for the easiest solution and removed the decimal.
=> #439 easy fix

docs/1_4_release_notes.rst, juntagrico/templates/management_lists/assignments.html
=> #424 more filter options for assignment overview

docs/1_4_release_notes.rst, juntagrico/util/temporal.py
first commit is the actual fix: the membership_end_date unecesarily calculated a future date from the offset again, which had no impact before because calculate next included today #468 
The rest is refactor to improve readability
=> Fix membership_end_date

juntagrico/admins/member_admin.py
=> #419 filter and show member address in admin

docs/1_5_release_notes.rst, docs/settings.rst, juntagrico/config.py, juntagrico/mailer/__init__.py, juntagrico/mailer/formemails.py, juntagrico/management/commands/mailtexts.py, juntagrico/templates/base.html, juntagrico/templates/cookie.html, juntagrico/templates/mails/member/password_reset.txt, testsettings.py
Remove the deprecated settings
=> cleanup ADMINPORTAL_NAME and ADMINPORTAL_SERVER_URL

docs/addons.rst, docs/index.rst, juntagrico/util/addons.py
=> addon config documentation and some refactor

docs/1_4_release_notes.rst, juntagrico/templates/area.html, juntagrico/templates/base.html, juntagrico/templates/home.html, juntagrico/templates/jobs.html
=> Fix area jobs

docs/1_5_release_notes.rst, juntagrico/static/juntagrico/external/attachment_appender.js
=> #470 remove uploaded attachment

.github/workflows/juntagrico-ci.yml, docs/1_5_release_notes.rst, juntagrico/admin.py, juntagrico/admins/area_admin.py, juntagrico/admins/billing_period_admin.py, juntagrico/admins/delivery_admin.py, juntagrico/admins/depot_admin.py, juntagrico/admins/inlines/subscription_part_inlines.py, juntagrico/admins/job_admin.py, juntagrico/admins/job_type_admin.py, juntagrico/admins/location_admin.py, juntagrico/admins/one_time_job_admin.py, juntagrico/admins/subscription_admin.py, juntagrico/admins/subscription_product_admin.py, juntagrico/admins/subscription_size_admin.py, juntagrico/admins/subscription_type_admin.py
I don't know why I never thought of these.
Will also help with the problem of scrolling through too long drop downs because usally you know exactly which entry you want and are not browsing for a suitable item
=> auto complete fields in the admin

docs/settings.rst, juntagrico/config.py, juntagrico/entity/__init__.py, juntagrico/lifecycle/share.py, juntagrico/templates/manage_shares.html, juntagrico/util/temporal.py, juntagrico/views_subscription.py, requirements.txt
=> #536 Add config for membership cancellation notice period

juntagrico/templates/snippets/snippet_subscription_change_extra_sub.html
Small modification to improve readability
=> Language: rephrase extra-sub cancellation rule

juntagrico/admins/subscription_size_admin.py, juntagrico/admins/subscription_type_admin.py
Search was broken due to typo in code
=> Fix subscription type admin search

juntagrico/templates/cancelmembership.html
on the membership cancellation page
=> improve wording

juntagrico/forms.py, test/test_profile.py
=> fix member cancellation if member has cancelled but not paid back share

juntagrico/views_admin.py
=> ask for login when opening versions page

juntagrico/dao/jobdao.py, juntagrico/entity/jobs.py, juntagrico/templatetags/juntagrico/widgets.py
If you guys want me to - and give me some guidance - I can write a/some tests for the changes, too.
=> Order upcoming jobs by date

juntagrico/templates/home.html
=> Fix title on open jobs on front page

juntagrico/signals.py, juntagrico/views.py
first steps for #426
- Added Signals that trigger when member joins or leaves an activity area.
=> Area welcome mail

juntagrico/lifecycle/submembership.py
when old sub is cancelled but not yet deactivated.
fixes #644
=> Allow order of new sub

juntagrico/admins/subscription_admin.py, juntagrico/resources/subscription.py
* Add export of all subscription parts
=> Sub part export

juntagrico/templates/juntagrico/my/subscription/snippets/part_list.html
=> fix: cancellation of subscription #669

docs/reference/settings.rst
I added a sentence to clarify the effect of the provided urls.
=> improve documentation about external documents

juntagrico/templates/cancelmembership.html, juntagrico/tests/test_profile.py, juntagrico/views/__init__.py
=> fix: allow membership cancellation if all subscriptions are cancelled #685

juntagrico/fixtures/test/members.json, juntagrico/tests/test_subs.py, juntagrico/views_subscription.py
=> fix: notify admin about part change #683

juntagrico/lifecycle/sub.py
Apply #647 also on cancellation/deactivation via admin
=> don't delete parts - fix up #647

juntagrico/entity/member.py, juntagrico/fixtures/test/areas.json, juntagrico/fixtures/test/members.json, juntagrico/templates/mail_sender.html, juntagrico/tests/__init__.py, juntagrico/tests/test_areas.py, juntagrico/tests/test_mailer.py, juntagrico/views_admin.py, testsettings.py
=> fix: Ensure "from" email address options in email sender form are unique #690

juntagrico/templatetags/juntagrico/widgets.py
=> fix assignment count in widget #702

juntagrico/entity/jobs.py, juntagrico/tests/test_manage_cmds.py
=> fix: deduplicate job reminder recipients #704

juntagrico/templates/juntagrico/my/subscription/snippets/part_list.html
=> fix: show cancel option for extras in part list #717

juntagrico/forms.py, juntagrico/templates/juntagrico/my/subscription/none.html, juntagrico/templates/juntagrico/my/subscription/single.html, juntagrico/templates/juntagrico/snippets/documents.html, juntagrico/templates/profile.html
=> member: Add documents to membership and subscription overview #678

juntagrico/forms.py, juntagrico/static/juntagrico/css/juntagrico.css, juntagrico/templates/memberjobs.html, juntagrico/util/temporal.py, juntagrico/views/job.py, testsettings.py
- Implement #487 
- Show assignments by business year and show totals
- Show info if has co-members, that only own assignments are shown and link to subscription overview
=> Member: Make assignment view clearer #487 

juntagrico/admins/tour_admin.py, juntagrico/entity/depot.py
- Fix crash when searching in admin of tour
- Remove broken link in admin to view tour on front page
=> fix: search in tour admin and remove broken "show on website" link

juntagrico/entity/__init__.py, juntagrico/lifecycle/share.py, juntagrico/lifecycle/sub.py, juntagrico/lifecycle/submembership.py, juntagrico/tests/test_sub_admin.py, testsettings.py
- Fixes #715
- Fixes adding deactivated subscription in admin
=> fix: Adding cancelled and/or deactivated subscription in admin #715

juntagrico/templates/juntagrico/my/depot/snippets/depot_summary.html
Added a button "Depot Details" to address #763 
I didn't know how to test translations, i.e. where to change the language in development mode.
=> member: add a button to depot details page

juntagrico/tests/__init__.py, juntagrico/views/manage.py
=> fix: don't show subs without parts in pending changes list

juntagrico/static/juntagrico/css/juntagrico.css, juntagrico/static/juntagrico/js/juntagrico.js, juntagrico/templates/juntagrico/manage/base.html, juntagrico/templates/juntagrico/manage/member/canceled.html, juntagrico/templates/juntagrico/manage/share/canceled.html, juntagrico/templates/juntagrico/manage/subscription/depot/changes.html
=> Fix tables headers everywhere

juntagrico/admins/filters.py, juntagrico/admins/subscription_admin.py, juntagrico/resources/subscription.py
implements #697
- Add filter options to subscription admin
- Fix: respect applied filters during subscription export
- Add primary member postal address to export
=> admin: subscription export improvements and fixes

juntagrico/admins/job_admin.py, juntagrico/admins/one_time_job_admin.py, juntagrico/entity/jobs.py
Show duration, multiplier pinned and canceled information
=> admin: Add columns in job admin list

pyproject.toml
For security
https://www.djangoproject.com/weblog/2025/jun/04/security-releases/
=> use django >= 4.2.22
