- juntagrico/templates/cancelmembership.html
- juntagrico/templates/cancelsubscription.html
- juntagrico/templates/contact.html
- juntagrico/templates/contact_member.html
- juntagrico/templates/mail_sender.html
The previous formatting caused whitespaces in the textareas
> Remove whitespace in textareas

- juntagrico/templates/mails/welcome_mail.txt
New members were receiving the welcome mail with special twig characters falsely appended to the password string hindering them from logging in.
> Fix bad characters in password in welcome mail

- juntagrico/templates/createsubscription/select_subscription.html
There was a space after the dash, i.e.
Juntagrico-Mitglied vs. Juntagrico- Mitglied
(I hope I don't annoy you with PR like these :-) )
> remove space after dash

- juntagrico/templates/exports/depotlist.html
With more members per subscription, sometimes 14 rows do not fit onto the page anymore for ortoloco. Let's save some space on the top of the page!
> Depot list remove header spacing to better fit onto page

- juntagrico/entity/depot.py
Invisible extra subs should not appear on top under "total" sum.
> Depot list: ignore invisible extra subs for total sum

- juntagrico/templates/messages/job_assigned.html
We had the feedback that "Zusammen mit 0 weiteren Personen" is confusing.
> Do not show "Zusammen mit" if it is 0

- juntagrico/dao/assignmentdao.py
- juntagrico/dao/jobdao.py
- juntagrico/dao/memberdao.py
Some convertions did not yield the expected results.  Assignments, that where close to the beginning of the business year were not counted.
`localize()` is the function, that "adds" the timezone information to a naive time (https://stackoverflow.com/a/13346065).
Found [here in Troubleshooting 3](https://docs.djangoproject.com/en/3.0/topics/i18n/timezones/#time-zones-faq).
> Fix convertion to timezone aware date

- juntagrico/entity/subs.py
- juntagrico/templates/management_lists/typechangelist.html
- juntagrico/templates/snippets/snippet_subscription_change_size.html
- juntagrico/templates/subscription.html
- juntagrico/templatetags/subscription.py
this solution will collapse (or not diplay) all levels which have only one sibling
since it is clear that it is milk for basimilch or  vegetables for meh als gmües since it is the only one
but may be if there is more than one product this does not make sense any more, maybe this is somethin i have to adapt but then the recursion has to be adapted 
maybe all the collapsing should not be done this would make the code far more easier and would allways be right
also it takes the types long name otherwise the size name since for example with ortoloco the type name is not meaningfull to the member
> #209 recursion for the win

- juntagrico/templates/subscription.html
There was confusion for some members what that means, needed clarification
> Clarify mail address not confirmed text in sub view

- juntagrico/templates/createsubscription/select_shares.html
Replace "Deine Anteilscheine" with "Neue Anteilscheine" to make clear that the input field contains the number of NEW shares for the member.
> Make share creation text more specific regarding NEW shares

- juntagrico/entity/subtypes.py
- juntagrico/forms.py
Currently, the products do not have a default order on the create subscription page and thus their order can change and is unpredictable. Let's introduce this quick fix / workaround to at least fix the order to the order of creation (reflected by primary key).
> Fix default order on create subscription page

- juntagrico/management/commands/generate_depot_list.py
- juntagrico/util/subs.py
Keep this important logic of future depot list activation separate and make it usable in alternative depot list generation functions
> Refactor to separate future depot activation as function

- juntagrico/templates/exports/depot_overview.html
Before:
Moved the created on timestamp to the upper-right.
After:
> Fixed overlapping header in depot overview pdf.

- docs/1_4_release_notes.rst
- juntagrico/admins/assignment_admin.py
- juntagrico/admins/job_admin.py
- juntagrico/admins/subscription_admin.py
- juntagrico/entity/jobs.py
As Patricia described in slack: https://juntagrico.slack.com/archives/CGFPD8L2Y/p1635184079005900
- Assignments could not be edited since update
- On admin main page the "show" link is displayed instead of "edit". But the entries inside are actually editable.
> Fix assignment edit

- docs/1_4_release_notes.rst
- juntagrico/views_iso20022.py
- test/test_iso20022.py
Creating the payment file failed, when there was actually a payable share to export.
> fix share payment file export and test coverage

- juntagrico/util/temporal.py
Otherwise the first day of the business year would be treated differently from the second and following days.
Also reduced code duplication
> calculate_next should not include today

- docs/1_4_release_notes.rst
- juntagrico/entity/subtypes.py
- juntagrico/templates/createsubscription/summary.html
- juntagrico/templates/forms/subscription_type_field.html
resolves #447
I consider the trial subscription field in this implementation. The trial field has been hidden in the admin (in 1.3), but the trial duration was not. I think the trial field is not needed, it can be just trial duration != 0.
Also fixes the summary page, where subs with billing periods showed the wrong price.
> #447 show subscription min duration in order process

- docs/1_4_release_notes.rst
- juntagrico/entity/member.py
- juntagrico/mailer/adminnotification.py
- juntagrico/management/commands/mailtexts.py
- juntagrico/templates/createsubscription/select_shares.html
- juntagrico/templates/mails/admin/subscription_created.txt
- juntagrico/util/management.py
- juntagrico/util/sessions.py
- juntagrico/view_decorators.py
- juntagrico/views_create_subscription.py
- juntagrico/views_subscription.py
- test/test_comember.py
- test/test_cs.py
- test/util/test.py
Fix some missing template variables and follow up issues after extending the tests.
Most critical is a fix in the order process of a sub for an existing member, that would lead to a 500 error on the summary page, due to the comment that is now expected on that form.
Instead of removing the comment field in that case, I included the comment in the admin notification mail for the new subscription. For the full signup process the comment will now appear in both emails (member and subscription creation notification), which is fine, because member could signup without a subscription and comment could be relevant for both.
In addition I blocked existing members with subscription from accessing the subscription order form. Trying to do the order process would result in a 500 error at the end and …
> Fix sub order process and template issues and extend tests

- docs/1_4_release_notes.rst
- juntagrico/entity/member.py
- juntagrico/views_subscription.py
One of our members managed to cancel all shares without cancelling the subscription or membership. Only the cancellation date was set, not the deactivation date.
I could not find a loop hole besides this one, where the member might have actively opened the URL with the modified id to cancel the "uncancallable".
> Check Share Cancellation

- docs/1_4_release_notes.rst
- juntagrico/admins/one_time_job_admin.py
Somebody in our cooperative figured out that one time jobs were not protected (anymore) :-)
> #90 fix: apply same past editing limitation to one time jobs

- docs/1_4_release_notes.rst
- juntagrico/entity/member.py
- juntagrico/templates/members.html
Issue was, that cancelled subscription would not show in the member list as their status was "cancelled" not "active".
I removed the condition, because, `subscription_current` only includes subscriptions that the member joined but did not leave yet, which by consistency rules must be an active (or cancelled) subscription.
A similar issue on the `join_subscription` would cause the co-member to not fully join a subscription if it was already cancelled (but leave the co-member in a waiting state). The case of trying to join an inactive subscription will, as before, raise a validation error in the consistency checks.
there is no other use of the `active` flag. That name is misleading and we might want to change it to `active_and_not_cancelled`, or remove it completely
> cancelled subscriptions are still active

- docs/1_5_release_notes.rst
- docs/settings.rst
- docs/theming.rst
- juntagrico/config.py
- juntagrico/templates/base.html
- juntagrico/templatetags/juntagrico/config.py
closes #427
I implemented both option: template and a list of static files.
The templates approach is more flexible, while the static files are easier to specify (no extra template file must be created).
I'm also thinking of the use case, where extensions give instructions to add a certain style or script to the settings.
> #427 custom page-wide scripts and styles

- docs/1_4_release_notes.rst
- juntagrico/dao/memberdao.py
- test/test_comember.py
- test/test_mailer.py
- test/util/test.py
In the mailer, when selecting "send to all members with shares" the expected result is, that it is only sent to members that hold shares that have not reached their termination date yet, i.e., members with voting rights.
> Email to all members with shares only with active shares

- juntagrico/admins/area_admin.py
- juntagrico/dao/activityareadao.py
- juntagrico/entity/jobs.py
- juntagrico/entity/subtypes.py
- juntagrico/management/commands/generate_testdata.py
- juntagrico/management/commands/generate_testdata_advanced.py
- juntagrico/templates/createsubscription/summary.html
- juntagrico/views_create_subscription.py
- juntagrico/views_subscription.py
- test/test_subs.py
- test/util/test.py
- Add a default activity area to subtypes
- adds member to the default activity area if added to the related sub
- contains migration on Subscri
TODO:
> feat: add member to default activity area on sub join

- docs/1_5_release_notes.rst
- docs/settings.rst
- juntagrico/config.py
- juntagrico/static/juntagrico/js/initMailer.js
- juntagrico/templates/mail_sender.html
Make the mailer tinymce editor field adjustable
Very specific example use case: We use the mailer templates to create the job list but then copy it from here to another newsletter tool. To simplify the workflow the font should be the correct one in the mailer editor already. For this I had to add `font-family` to the `valid_styles` options.
> Setting to override tinymce options of mailer view

- docs/1_5_release_notes.rst
- juntagrico/entity/jobs.py
- test/test_admin.py
fixes #532
for some reason we get an abstract `Job` instance in `can_modify` in some cases (e.g. when deleting a job), but not in others (e.g. when editing an assignment).
Doing an upcast here if needed.
> fix deletion of jobs

- juntagrico/entity/subs.py
- juntagrico/util/temporal.py
- requirements.txt
- test/test_assignments.py
- test/util/test.py
this fixes the critical part of #442 and applies a minimal fix based on #536.
Requires assignments of under-year parts are calculated correctly.
For trial parts it is assumed, that no discount is applied, i.e. the required assignments set in the trial sub are always the same.
> Fix required assignments (backport for 1.4.x)

- juntagrico/entity/member.py
- juntagrico/entity/subs.py
- test/test_assignments.py
- test/util/test.py
with variable duration and on year change
- If trial is stopped earlier, assignments are discounted, if it takes longer, more assignments are needed.
- Trials around year change now calculate the correct amount of assignments needed in the current year.
- Fix day count in general: the first day of a period was not counted correctly.
> fix required assignment count for trial subs 

- juntagrico/templates/mails/email.txt
characters like apostrophes (') where wrongly HTML escaped in some strings. Disable escaping in general in plain text emails
> fix special chars in plain text emails

- juntagrico/entity/billing.py
- juntagrico/entity/depot.py
- juntagrico/entity/jobs.py
- juntagrico/entity/location.py
- juntagrico/entity/mailing.py
- juntagrico/entity/member.py
- juntagrico/entity/share.py
- juntagrico/entity/subs.py
- juntagrico/entity/subtypes.py
- juntagrico/migrations/0038_pre_1_6.py
fixes #602
- Removed all length limitations on text area fields. Including for mail templates.
> remove length limitation on all text fields

- juntagrico/util/ical.py
For some reason, NAME doesn't seem to work. When setting the 'NAME' property of the event, the title is empty. 
However, using 'SUMMARY' properly populates the title. I have tested by generating an ical event by subscribing to a job then importing it in both Google Calendar and Apple Calendar. 
With both, using 'SUMMARY', the event had the appropriate title.
> Use the SUMMARY property of the Event instead of NAME for the event title

- docs/intro/advanced.rst
- juntagrico/forms.py
Form texts can not be modified by template overriding.
Modification should be simplified and the way to do so should be documented.
solves #588 (minimal solution)
> Form Text Customization

- juntagrico/templates/mails/member/job_reminder.txt
addresses https://github.com/juntagrico/juntagrico/issues/619
Resulting email would look as shown below.
One could argue that there should be some punctuation or orther forms of separation between different contants and or user emails. Happy to look into it if needed.
> escape contacts in job reminder email

- juntagrico/templates/createsubscription/select_depot.html
- juntagrico/templates/depot.html
- juntagrico/templates/depot_change.html
- juntagrico/templates/job.html
- juntagrico/templates/snippets/scripts/leaflet.html
fixes #618
Note: The marker icon worked already before, because it didn't use the `{% static %}` template function for the leaflet css. This was unclean so it was fixed as well.
> Fix leaflet marker icon when using ManifestStaticFileStorage

- juntagrico/util/ical.py
The `.ics` files sent in email confirmations didn't have any title when imported into Google Calendar or Outlook.
Changed the field name for the `VEVENT` title from the undefined `NAME` to `SUMMARY`. Now imports correctly. 
cf. https://icalendar.org/iCalendar-RFC-5545/3-6-1-event-component.html
fixes https://github.com/juntagrico/juntagrico/issues/657
> Fixed ical VEVENT title

- juntagrico/management/commands/generate_testdata_advanced.py
An example of how to run it:
python manage.py generate_testdata_advanced --depots 18 --product Gemüse/1 Obst/1,2 Brot Eier Tofu --days 2 4
will create Gemüse with size 1, Obst with size 1 and size 2, etc
Replaces the pull request #655
> More arguments to generate test data, and fixed subscriptions added.

- juntagrico/admins/forms/job_copy_form.py
- test/test_adminforms.py
(cherry picked from commit 314c836ad14b58de5ef04482a17aed6ecd794b08)
If USE_TZ is False in the setting the datetime is now kept naive
All test cases should use [setUpTestData](https://docs.djangoproject.com/en/4.2/topics/testing/tools/#django.test.TestCase.setUpTestData) instead of setUp, as it is faster in most cases.
> fix: make mass job copy work if USE_TZ=False

- docs/reference/settings.rst
- juntagrico/config.py
- juntagrico/templates/createsubscription/select_shares.html
- juntagrico/util/sessions.py
- setup.cfg
implements #623 partially
New Setting `REQURIED_SHARES`, specifies how many shares must be ordered during registration. Defaults to 1 to match previous behaviour
> member: Flexible required minimum shares amount on registration #623

- juntagrico/admins/forms/job_copy_form.py
- juntagrico/admins/job_admin.py
- juntagrico/entity/contact.py
- juntagrico/tests/test_admin.py
- juntagrico/tests/test_adminforms.py
- setup.cfg
The additional description, duration override and contacts of a job were not copied to the new jobs in the mass copy function. The fields are not copied and can also be edited in the copy process.
> fix: copy all relevant fields in job mass copy

- juntagrico/queryset/subscription.py
- juntagrico/templatetags/juntagrico/widgets.py
In the sidebar widget the future assignments were counted, but displayed wrong. Reverting to original behavior, where future assignments are not counted.
fixes #682
> fix: don't count future assignments #682

- juntagrico/lifecycle/submembership.py
Fix this error message when adding subscriptionmembership without subscription.
```
RelatedObjectDoesNotExist at /admin/juntagrico/subscriptionmembership/add/
SubscriptionMembership has no subscription.
```
> fix: error when adding sub membership in admin without specifying subscription

- juntagrico/entity/jobs.py
- juntagrico/entity/member.py
- juntagrico/lifecycle/sub.py
- juntagrico/lifecycle/submembership.py
- juntagrico/lifecycle/subpart.py
when using manage.py loaddata the presave signals are triggered but the actions should usually be ignored to avoid accessing objects that don't exist yet.
> fix: ignore pre_saves for loaddata

- juntagrico/templates/juntagrico/my/subscription/snippets/banners/canceled.html
The banner is falsely showing the cancellation date twice instead of the deactivation date.
> fix: subscription deactivation date visible to member in subscription overview

- juntagrico/lifecycle/sub.py
- juntagrico/lifecycle/submembership.py
- juntagrico/lifecycle/subpart.py
- juntagrico/tests/test_sub_admin.py
Deactivation of subscriptions should be done via the cancellation lists. However some admins found a workaround to do deactivation via the django admin. This previously worked by first setting the deactivation date or the parts, then the leave dates on the subscription memberships and finally the deactivation date of the subscription.
Since juntagrico 1.6 the form checks if the last member leaves the subscription and raises a validation error as the subscription would be inconsistent in that case. Thus the above approach for deactivation stopped working for them.
This fix, enables the deactivation of the subscription in the django admin, by setting the deactivation date of the subscription. The date will be propagated to empty leave dates and part deactivation dates. Deactivation also …
> fix: subscription deactivation via django admin

- juntagrico/templates/management_lists/assignments.html
Fix assignment management list for the case that a subscription exists without a primary member.
> fix: assignment management list with inconsistent subscription

- juntagrico/admins/inlines/assignment_inline.py
So far 1 slot was hidden in the assignment inline forms, if the job had infinite slots
> fix: admin assignment inline display for infinite slots

- juntagrico/templates/depot_change.html
- juntagrico/templates/juntagrico/my/depot/snippets/change_pending_info.html
- juntagrico/templates/juntagrico/my/depot/snippets/depot_summary.html
display info in overview when depot change is pending and formulate info after change more accurately
The same message is shown after changing the depot. Previously after changing a depot the message said, that activation would happen after depot list generation. As list generation may happen without updating depots (especially since #574), this is inaccurate and was probably cryptic to the member anyway.
> member: Display accurate info on changed depot

- juntagrico/tests/test_profile.py
- juntagrico/tests/test_subs.py
- juntagrico/util/auth.py
> fix: Don't send password reset emails to inactive members #318

- juntagrico/entity/__init__.py
- juntagrico/tests/test_sub_admin.py
#713 did not work if a future deactivation date is set. This PR fixes that.
> Fix: Future subscription deactivation via django admin

- juntagrico/templates/manage_shares.html
- Allow cancellation of unpaid shares if they are not needed for a subscription. Implements #670
- The shares will then be listed as cancelled ("Storniert") and aren't deleted
- Clean up share overview
> member: Allow cancellation of unpaid share and clean up share view #670

- juntagrico/admins/member_admin.py
- juntagrico/templates/profile.html
Implements #396: Member number can now be set in admin and will be shown to member in profile if set
> admin/member: show member number in admin and to member (if set) #396

- juntagrico/mailer/__init__.py
- juntagrico/management/commands/generate_testdata.py
- juntagrico/management/commands/mailtexts.py
- testsettings.py
As temporary members and other objects are created during the mailtexts command, a notification email would leak when executed in production. This is now prevented.
> fix: don't send any emails during mailtexts command #729

- juntagrico/views_subscription.py
Fixes this https://github.com/juntagrico/juntagrico/issues/683#issuecomment-2359345395
Fix: Show the correct new part in notification email on subscription part type change
> fix: use the correct new subscription type in notification #683

- juntagrico/static/juntagrico/js/juntagrico.js
If one depot location does not have coordinates, the map in the depot selection view broke
> fix: show depots on map in selection view, even if only some depots have coordinates

- juntagrico/templates/snippets/snippet_jobs.html
Due to a bug, only admins could see the shortcuts on the frontpage to create jobs.
> fix: show job creation links

- docs/reference/settings.rst
- juntagrico/config.py
- juntagrico/mailer/adminnotification.py
- juntagrico/tests/test_jobs.py
Anticipating, that some will want to reduce the amount of the new job signup notification emails.
By default signups without message now cause no notification but can be enabled with `ENABLE_NOTIFICATIONS = ['job_subscribed']`. Changing or unsubscribing from a job without message will send a notification, but can be disabled with `DISABLE_NOTIFICATIONS`. See Docs.
This is a quick solution until #542 will allow for more flexibility.
Added settings ENABLE_NOTIFICATIONS and DISABLE_NOTIFICATIONS
> admin: Setting to reduce job signup notification emails

- juntagrico/entity/subtypes.py
- juntagrico/templates/createsubscription/summary.html
In the summary at the end of the signup a trial subscription price was shown as "per year", which is incorrect. Now it just shows the price. The  duration info in the next sentence makes it clear, that the price is for that period.
> fix: price of trials is not per year

- juntagrico/apps.py
- juntagrico/fixtures/test/members.json
- juntagrico/models.py
- juntagrico/signals.py
- juntagrico/tests/test_shares.py
- juntagrico/views_subscription.py
Admin notification on canceled shares is documented (in permissions reference) but not implemented.
This PR adds the implementation.
> fix: send share canceled notification email

- juntagrico/entity/member.py
- juntagrico/forms.py
- juntagrico/tests/test_comember.py
When adding an existing member as a co-member on the same day that that member left another subscription, the server crashes (500).
This fix handles the case of adding a co-member on the same day they left another subscription by adding them to the new subscription tomorrow.
> fix: Allow adding co-member on same day the left another subscription

- juntagrico/templates/cancelmembership.html
So far members were shown this membership cancellation page, if they still had shares required by a subscription.
The description did not make it clear, that an action was required by the member.
this PR makes the description clearer and highlights the relevant text.
#554 should make it easier, to do the requested steps, i.e. cancel the subscription, directly on this cancellation page.
> member: Clearer explanation on membership cancellation page

- juntagrico/admins/forms/import_export_form.py
This allows selection of entire business year, even if it starts mid year and no jobs have been created in the next year.
> fix: extend assignment count year range in subs export

- juntagrico/admins/__init__.py
- juntagrico/admins/forms/job_copy_form.py
- juntagrico/admins/job_admin.py
- juntagrico/config.py
- juntagrico/templatetags/juntagrico/common.py
- juntagrico/tests/test_adminforms.py
- juntagrico/views/api.py
Fixes the dynamic preview of #752 and adds it to the job copy form as well.
Clean up job copy form in general.
> fix: Display type description correctly in job admin and during mass copy

- juntagrico/admins/job_type_admin.py
- juntagrico/tests/test_admin.py
When an area admin opened the autocomplete field for the jobtype in the job admin change/add form, the server would crash, returning no results.
The issue seems to be the annotation in the queryset. It is not needed for the autocomplete field, so the solution is to not apply it in that case.
> fix: jobtype autocomplete in job admin form for area admins

- juntagrico/static/juntagrico/css/juntagrico.css
- juntagrico/templates/juntagrico/manage/base.html
Fixes regression from #770: The row with buttons and search field on some datatables must be sticky when scrolling.
> fix sticky datatable top

- juntagrico/templates/juntagrico/job/snippets/edit_assignment.html
- juntagrico/templates/juntagrico/job/snippets/participant_list.html
- juntagrico/templates/juntagrico/my/assignment/snippets/subscription_overview.html
- juntagrico/templates/juntagrico/widgets/assignment_progress.html
- juntagrico/templates/juntagrico/widgets/assignment_progress/text_hours.html
- juntagrico/views/subscription.py
These texts previously did not consider the assignment unit. This PR fixes that
> Fix wording for assignments when using hours

- juntagrico/templates/juntagrico/manage/subscription/recent.html
To make the events grouped and ordered more intuitively.
I.e. when sorting by date (newest first), the activation event of a sub should appear below the deactivation event of the same sub etc.
> admin: Define multi-column sort for date column in recent subscription changes management table

- juntagrico/queryset/subscription.py
parts are activated and deactivated the same day to indicate that they were never active.
> fix: don't count required assignments of 1-day parts

- juntagrico/templates/mail_sender_result.html
- juntagrico/views_admin.py
Instead of a server fault, display error message returned by SMTP server.
> admin: Show error when sending email fails
